name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Konfiguracja Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalacja zależności systemowych
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake \
            libffi-dev libssl-dev lld

      - name: Instalacja Buildozer i Cython
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Kompilacja APK (Buildozer)
        run: |
          buildozer -v android debug

      - name: Zapisanie gotowego pliku APK
        uses: actions/upload-artifact@v4
        with:
          name: PixelMatrix-App-APK
          path: bin/*.apk
