name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kompilacja APK (Buildozer)
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: master

      - name: Zapisanie pliku APK jako Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PixelMatrix-App-APK
          path: ${{ steps.buildozer.outputs.filename }}
